# Use following keys for types #
#   bool    = 2                #
#   integer = 3                #
#   float   = 4                #
#   string  = 5                #

- key: "flip_percent"
  type: 4
  value: 0.80

- key: "flip_amount"
  type: 3
  value: 1